config/routes.rb
Rails.application.routes.draw do

  

  resources :users
  root :to => redirect('/links')
  resources :links do 
    member do
    put 'upvote'
    put 'remove'
    end
  end
  
  resources :links
  get '/report', to: 'links#report'
  put '/report' => 'links#reportsend'
  
  
  get 'auth/google_oauth2/callback', to: 'users#create', as: 'signin'
  get '/signout' ,to: 'users#destroy', as: 'signout'
  put '/new_admin' => 'users#new_admin', as: 'new_admin'
  get '/admin_page' => 'links#admin_page', as: 'admin_page'
  get '/approval' => 'links#approve_link', as: 'approval'
  post 'approve_or_decline_link' => 'links#approve_or_decline', as: 'approve_or_decline_link'
  get '/page' => 'links#page', as: 'page'
end

app/models/link.rb
require 'uri'

class Link < ActiveRecord::Base
  
  validates :url, presence: true, uniqueness: true, format: { with: URI.regexp, message: "must be in the format: http://www.example.com"} #, message: "You need to enter a URL"
  validates :name, presence: true, uniqueness: true#, message: "You need to give the URL a name"
 #, :message => "Not a properly formatted URL, make sure to include \"http://\" or \"https://\""}
  #validates :url, :url => true
    
  def self.all_categories
    return ["Get Acclimated & Get Inspired", "Get Smart & Get Informed", "Get Connected & Get Taught", "Get Experience", "Get Organized", "Get Funded"]
  end
  
  # def valid_url
  #   uri = URI.parse(url)
  #   uri.kind_of?(URI::HTTP)
  # rescue URI::InvalidURIError
  #   false
  # end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    protect_from_forgery except: :page
    
    # before_filter :authenticate, only: [:new] 
    
    def link_params
        params.fetch(:link).permit(:name, :url, :upvotes, :category, :comments, :reportreason, :otherreportreason, :reportname, :link)
    end
    
    def show
        id = params[:id] # retrieve link ID from URI route
        @link = Link.find(id) # look up link by unique ID
        # will render app/views/links/show.<extenstion> by default
    end
    
    def index
        # LinksHelper.test
        #@links = Link
        
        
        #session[:intern_display] = session[:intern_display] || "none"
        
        @inspirations = Link.where(category: "Get Acclimated & Get Inspired", status: true).each_slice(5).to_a
        @internships = Link.where(category: "Get Smart & Get Informed", status: true).each_slice(5).to_a
        @grants = Link.where(category: "Get Connected & Get Taught", status: true).each_slice(5).to_a
        @jobs = Link.where(category: 'Get Experience', status: true).each_slice(5).to_a
        @other = Link.where(category: "Get Organized", status: true).each_slice(5).to_a
        @funded = Link.where(category: "Get Funded", status: true).each_slice(5).to_a
        @hired = Link.where(category: "Get Hired", status: true).each_slice(5).to_a
        session[:links] = @links
        @number_of_unapproved = Link.where(status: false).size
        
    end
    
    def new
        if !session[:authenticated]
            session[:error] = "Must be logged in to add links"
            redirect_to root_path
        end
        @link = Link.new
    end

    def create

        if session[:admin]
            @link = Link.new(link_params.merge({:status => true, :upvotes => 0, :email => current_user.email, :upvoters => '' }))
        else
            @link = Link.new(link_params.merge({:status => false, :upvotes => 0, :email => current_user.email, :upvoters => '' }))
            session[:new_message] = "Your link is now pending approval from an admin"
        end
        
        if @link.save or session[:rspec_test]
            AddlinkMailer.linkrequest_email(@link).deliver_now
            redirect_to links_path
        else 
             
             @link.delete
             
             render 'new'
        end
  
    end
    
    def edit
        @link = Link.find params[:id]
    end
    
    #def report
     #   @link = Link.find params[:id] 
    #end
    
    def update
        
        redirect_to links_path
    end

    def destroy
        redirect_to links_path
    end
    
    def report
        
        if !session[:authenticated]
             session[:error2] = "Must be logged in to report links"
             redirect_to root_path
        end
        
        reportname = params[:reportname]
        reportreason = params[:reportreason]
        otherreportreason = params[:otherreportreason]
        
        @link = Link.find_by name: reportname
    end
    
    def reportsend
        #logger.info "!!!!!!!"+params.to_s
        #@link = Link.find params[:link_id]
        #@link.update_attributes!(link_params)
        #@link.update(reportreason: params[:reportreason])
       
       
        reportname = params[:reportname]
        reportreason = params[:reportreason]
        otherreportreason = params[:otherreportreason]
  
        @link = Link.find_by name: reportname
        
        if @link == nil 
            session[:reportname] = reportname
            session[:report_error] = "No link with that name exists"
            render 'report'
        elsif @link != nil
           
            if reportreason == "Other"
            AddlinkMailer.otherreportrequest_email(reportname, otherreportreason).deliver_now
            else
            AddlinkMailer.reportrequest_email(reportname, reportreason).deliver_now
            end
            
            session[:reported] = "Your report has been forwarded to an admin."
            redirect_to links_path
            
        end
        
        #redirect_to links_path
    end
    
    
    def approve_link
        if !session[:admin]
            redirect_to links_path
        end
        @links = Link.where(status: false)
    end
    
    def approve_or_decline
        @link = Link.find(params[:link_id])
        @feedback = params[:feedback]
        if params[:commit]=="Approve"
            AddlinkMailer.requestapproved_email(@link, @feedback).deliver_now
            @link.update(status: true)
        else
            AddlinkMailer.requestdenied_email(@link, @feedback).deliver_now
            @link.destroy
        end
        @links = Link.where(status: false)
        respond_to do |format| 
            format.js
        end
    end

    def upvote
        @link = Link.find(params[:id])
        upvoters = @link.upvoters.split(';')
        user_id = params[:user_id]
        if upvoters.include?(user_id)
             @link.upvotes -= 1
             @link.upvoters.slice!("#{user_id};")
        else
             @link.upvotes += 1
             @link.upvoters += "#{user_id};"
        end
        @link.save
        
        respond_to do |format|
            format.js 
        end
    end
    
    def remove 
        
        @link = Link.find(params[:id])
        Link.delete(@link)
        
        respond_to do |format|
            format.js 
        end
        
    end
    
    def page
        @internships = Link.where(category: "Get Smart & Get Informed", status: true).each_slice(5).to_a
        @inspirations = Link.where(category: "Get Acclimated & Get Inspired", status: true).each_slice(5).to_a
        @grants = Link.where(category: "Get Connected & Get Taught", status: true).each_slice(5).to_a
        @jobs = Link.where(category: 'Get Experience', status: true).each_slice(5).to_a
        @other = Link.where(category: "Get Organized", status: true).each_slice(5).to_a
        @funded = Link.where(category: "Get Funded", status: true).each_slice(5).to_a
        @hired = Link.where(category: "Get Hired", status: true).each_slice(5).to_a
        
        session[:intern_page_num] = session[:intern_page_num].to_i+params[:intern_incre].to_i   
        session[:grant_page_num] = session[:grant_page_num].to_i+params[:grant_incre].to_i  
        session[:job_page_num] = session[:job_page_num].to_i+params[:job_incre].to_i  
        session[:other_page_num] = session[:other_page_num].to_i+params[:other_incre].to_i  
        session[:fund_page_num] = session[:fund_page_num].to_i+params[:fund_incre].to_i
        session[:insp_page_num] = session[:insp_page_num].to_i+params[:insp_incre].to_i
        session[:hired_page_num] = session[:hired_page_num].to_i+params[:hired_incre].to_i
        
        change = ""
        params.each do |key, value|
            if key=~/.+incre/
                change = key
                break
            end
        end
        @change = change.chomp("_incre")
        respond_to do |format|
            format.js 
        end
    end
end

app/helpers/links_helper.rb
module LinksHelper
    # def test
    # end
end

app/views/links/_hire.html.erb
<% @hired[session[:hired_page_num]].each do |hir| %>
   <div class = <%= hir.name.gsub(" ", "_") %><%= hir.upvotes %> id = "hired" style="display: block"> 
      <!--Vote Button-->
      <div class = "inline" id = <%= hir.name + "votes" %>> 
      <div class = "inline" id = <%= hir.name + "thumbup" %>>
      <% if current_user %>
      <% if hir.upvoters.split(';').include?("#{current_user.id}") %> 
      <%= link_to image_tag("uparrowtrue.png",:size => "20x20"), upvote_link_path(hir,user_id: current_user.id), remote: true, method: :put %>
      <% else %>
      <%= link_to image_tag("uparrow.png",:size => "20x20"), upvote_link_path(hir,user_id: current_user.id), remote: true, method: :put %>
      <% end %>
      <% end %>
      </div>
      <!--URL NAME URL-->
      <a href= <%= hir.url %> > <%= hir.name %> </a> 
      </div>
      
      <!--Vote Count-->
      <div class = "inline" id = <%=hir.name%> > 
      <div class = "animated zoomIn"> 
      <%= hir.upvotes %> 
      
      </div>
      </div>
    <% if current_user %>
      <% if current_user.admin %>
        <div class = "inline" id = "report"> 
          <%= link_to image_tag("deletex.png",:size => "10x10" ), remove_link_path(hir), remote: true, method: :put %>
        </div>
     <%end %>
     <% end %>
  </div>
  <% end %>
  <div id="hiredLink" class = "zzzz" style="display: block">
        <% if @hired.length>1  %>
        view more:
        <% end %>
        <% if session[:hired_page_num]>0%>
        <%= link_to '< prev', page_path(hired_incre: -1), remote: true %>
        <% end %>
        <% if session[:hired_page_num]>0 && session[:hired_page_num]<@hired.length-1%>
        |
        <% end %>
        <% if session[:hired_page_num]<@hired.length-1%>
        <%= link_to 'next >', page_path(hired_incre: 1), remote: true %>
        <% end %>
      </div>

app/views/links/_insp.html.erb
<% @inspirations[session[:insp_page_num]].each do |inspir| %>
   <div class = <%= inspir.name.gsub(" ", "_") %><%= inspir.upvotes %> id = "inspiration" style="display: block"> 
      <!--Vote Button-->
      <div class = "inline" id = <%= inspir.name + "votes" %>> 
      <div class = "inline" id = <%= inspir.name + "thumbup" %>>
      <% if current_user %>
      <% if inspir.upvoters.split(';').include?("#{current_user.id}") %> 
      <%= link_to image_tag("uparrowtrue.png",:size => "20x20"), upvote_link_path(inspir,user_id: current_user.id), remote: true, method: :put %>
      <% else %>
      <%= link_to image_tag("uparrow.png",:size => "20x20"), upvote_link_path(inspir,user_id: current_user.id), remote: true, method: :put %>
      <% end %>
      <% end %>
      </div>
      <!--URL NAME URL-->
      <a href= <%= inspir.url %> > <%= inspir.name %> </a> 
      </div>
      
      <!--Vote Count-->
      <div class = "inline" id = <%=inspir.name%> > 
      <div class = "animated zoomIn"> 
      <%= inspir.upvotes %> 
      
      </div>
      </div>
     <% if current_user %>
      <% if current_user.admin %>   
        <div class = "inline" id = "report"> 
          <%= link_to image_tag("deletex.png",:size => "10x10" ), remove_link_path(inspir), remote: true, method: :put %>
        </div>
      <% end %>
      <% end %>
  </div>
  <% end %>
  <div id="inspirationLink" class = "zzzz" style="display: block">
        <% if @inspirations.length>1  %>
        view more:
        <% end %>
        <% if session[:insp_page_num]>0%>
        <%= link_to '< prev', page_path(insp_incre: -1), remote: true %>
        <% end %>
        <% if session[:insp_page_num]>0 && session[:insp_page_num]<@inspirations.length-1%>
        |
        <% end %>
        <% if session[:insp_page_num]<@inspirations.length-1%>
        <%= link_to 'next >', page_path(insp_incre: 1), remote: true %>
        <% end %>
      </div>

app/views/links/_intern.html.erb
<% @internships[session[:intern_page_num]].each do |intern| %>
   <div class = <%= intern.name.gsub(" " , "_") %><%= intern.upvotes %>  id = "internship" style="display: block"> 
      <!--Vote Button-->

      <div class = "inline" id = <%= intern.name + "votes" %>> 
      <div class = "inline" id = <%= intern.name + "thumbup" %>>
      <% if current_user %>
      <% if intern.upvoters.split(';').include?("#{current_user.id}") %> 
      <%= link_to image_tag("uparrowtrue.png",:size => "20x20"), upvote_link_path(intern,user_id: current_user.id), remote: true, method: :put %>
      <% else %>
      <%= link_to image_tag("uparrow.png",:size => "20x20"), upvote_link_path(intern,user_id: current_user.id), remote: true, method: :put %>
      <% end %>
      <% end %>
      </div>
      <!--URL NAME URL-->
      <a href= <%= intern.url %> > <%= intern.name %> </a> 
      </div>
      
     
      <!--Vote Count-->
      <div class = "inline" id = <%=intern.name%> > 
      <div class = "animated zoomIn"> 
      <%= intern.upvotes %> 
      </div>
      </div>
      
      <% if current_user %>
      <% if current_user.admin %>
        <div class = "inlinedelete" id = "report"> 
        <%= link_to image_tag("deletex.png",:size => "10x10" ), remove_link_path(intern), remote: true, method: :put %>
        </div>
      <% end %>
      <% end %>
      
  </div>
  
      <% end %>
      <div id="internshipLink" class = "zzzz" style="display: block">
        <% if @internships.length>1  %>
        view more:
        <% end %>
        <% if session[:intern_page_num]>0%>
        <%= link_to '< prev', page_path(intern_incre: -1), remote: true %>
        <% end %>
        <% if session[:intern_page_num]>0 && session[:intern_page_num]<@internships.length-1%>
        |
        <% end %>
        <% if session[:intern_page_num]<@internships.length-1%>
        <%= link_to 'next >', page_path(intern_incre: 1), remote: true %>
        <% end %>
      </div>

app/views/links/_other.html.erb
<% @other[session[:other_page_num]].each do |oth| %>
   <div class = <%= oth.name.gsub(" ", "_") %><%= oth.upvotes %> id = "other" style="display: block"> 
      <!--Vote Button-->
      <div class = "inline" id = <%= oth.name + "votes" %>> 
      <div class = "inline" id = <%= oth.name + "thumbup" %>>
      <% if current_user %>
      <% if oth.upvoters.split(';').include?("#{current_user.id}") %> 
      <%= link_to image_tag("uparrowtrue.png",:size => "20x20"), upvote_link_path(oth,user_id: current_user.id), remote: true, method: :put %>
      <% else %>
      <%= link_to image_tag("uparrow.png",:size => "20x20"), upvote_link_path(oth,user_id: current_user.id), remote: true, method: :put %>
      <% end %>
      <% end %>
      </div>
      <!--URL NAME URL-->
      <a href= <%= oth.url %> > <%= oth.name %> </a> 
      </div>
      
      <!--Vote Count-->
      <div class = "inline" id = <%=oth.name%> > 
      <div class = "animated zoomIn"> 
      <%= oth.upvotes %> 
      
      </div>
      </div>
      <% if current_user %>
      <% if current_user.admin %>
        <div class = "inline" id = "report"> 
          <%= link_to image_tag("deletex.png",:size => "10x10" ), remove_link_path(oth), remote: true, method: :put %>
        </div>
     <%end %>
     <% end %>
  </div>
  <% end %>
  <div id="otherLink" class = "zzzz" style="display: block">
        <% if @other.length>1  %>
        view more:
        <% end %>
        <% if session[:other_page_num]>0%>
        <%= link_to '< prev', page_path(other_incre: -1), remote: true %>
        <% end %>
        <% if session[:other_page_num]>0 && session[:other_page_num]<@other.length-1%>
        |
        <% end %>
        <% if session[:other_page_num]<@other.length-1%>
        <%= link_to 'next >', page_path(other_incre: 1), remote: true %>
        <% end %>
      </div>

app/views/links/_thumb.html.erb
<% if current_user %>
    <% if @link.upvoters.split(';').include?("#{current_user.id}") %> 
        <%= link_to image_tag("uparrowtrue.png",:size => "20x20"), upvote_link_path(@link,user_id: current_user.id), remote: true, method: :put %>
    <% else %>
        <%= link_to image_tag("uparrow.png",:size => "20x20"), upvote_link_path(@link,user_id: current_user.id), remote: true, method: :put %>
    <% end %>
<% end %>

app/views/links/_unapproved_links.html.erb
<% if @links %>
    <% @links.each do |link| %>
        <%= form_tag(approve_or_decline_link_path, remote: true) do %>
            <div id = "entry">   
                <div id = "name">
                    <p><%= link.name %></p>
                </div>
                <div id = "link">
                    <%= link_to "show site", link.url, target: "_blank"%>
                </div>
                <div id ="approve">
                    <%= submit_tag "Approve", class: "button", :data => {:confirm => "Are you sure you would like to aprove this link?" }%> 
                </div>
                <div id = "decline">
                    <%= submit_tag "Decline", class: "button", :data => {:confirm => "Are you sure you would like to decline this link?" }%>
                </div>
                <div id = "comments">
                    <%= text_area_tag "feedback", nil, placeholder: "Comments(optional)", rows: 3, cols: 53 %>
                </div>
                <%= hidden_field_tag "link_id", link.id %>
                <hr class = "line2">
            </div> 
        <%end%>
            
    <% end %>
<% end %>    

app/views/links/approve_link.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class = "animated fadeIn"> 
    <div align = "right">
      <div id = "admin">
      <%= form_tag("/new_admin", method: "put") do %>
      <div id = "admin"> 
        <%= label_tag(:email) %>
        </div>
        
        <%= text_field_tag(:email) %>
       
        <%= submit_tag("Add Administrator", :data => {:confirm => "Are you sure you would like to add an administrator?" })%>
        
        
      <% end %>
      </div>
      <strong><%= current_user.name %></strong>
      <%= link_to "Sign out", signout_path %>
    </div>
    
    <div align = "left">
        <%= session[:error] %>
        <%= session[:error] = nil%>
    </div>
    
    
   
    <header>
      <h2>
        <font color="#99012">Link Approval</font>
      </h2>
    </header> 
    <hr class = "line2">
    <div id = "approval" align = "center">
        <%= render partial: 'unapproved_links' %>
    </div>

    <div class = "leftalign" align = "center">
      <%= link_to "Back", links_path %>
    </div>
    
    </div>
    
  </body>
</html>

app/views/links/approve_or_decline.js.erb
$("#approval").html("<%= escape_javascript(render partial: 'unapproved_links') %>");

app/views/links/decline.js.erb
$("#approval").html("<%= escape_javascript(render partial: 'unapproved_links') %>");

app/views/links/edit.html.erb
<!DOCTYPE html>
<html>
</html>

app/views/links/new.html.erb
<!DOCTYPE html>
<html>
<head>
 <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Roboto+Mono:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class = "row"> 

  <h1><b><center> <br>
   <font face="Roboto Mono", color="#000000", size="70">PC<br>SE</font></center></b>
   </h1>
   </div>
    
  <h2><b><center> 
  
  <div class= "animated fadeIn">
   <font color="#99012">Request a Link</font></center></b>
   </div>
   </h2></br>
   
  <div class= "animated fadeIn">
   <p><i><center>An administrator will be notified of your link request after submission for approval.</center></i></p>
   </div>
 
        <div class = "animated fadeIn"> 
        <div class = "formalign"> 
        <%= form_for(@link) do |link| %>
          
          <div class="left"><div align="left">
          <p>Name</p></div>
          </div>
          <div class = "right"> 
          <%= link.text_field :name %> <br>
          </div><br><br>
          
          <div class="left"><div align="left">
          <p>URL</p></div>
          </div>
          
          <div class = "right"> 
          <%= link.text_field :url %> <br>
          </div><br><br>
          
          <div class= "left"><div align="left">
          <p>Category</p></div>
          </div>
          
          <div class = "right"> 
          <%= link.select :category, ['Get Acclimated & Get Inspired','Get Smart & Get Informed','Get Connected & Get Taught','Get Experience','Get Organized', 'Get Funded', 'Get Hired'] %></br></br>
          </div><br><br>
          
          <div class = "left"><div align="left">
          <p>Comments</p></div>
          </div>
          
          <div class = "right"> 
          <%= link.text_field :comments %>
          </div><br><br><br>
         
         
         
         <!--<div class = "inline" id = "linksAdd">--> 
         <div class="row">
         <div class="col-xs-5 col-xsoffset-4">
         <div align="center">
          <%= button_tag(type: 'submit', class: "btn btn-large btn-search btn-primary") do %>
            <i class="icon icon-search"></i> Request
          <% end %>&nbsp;&nbsp;&nbsp;
          <%= link_to "Back", links_path %>
          </div>
          </div>
          </div>
      
      
      
      
      
      </div>
      </div>
    

        <% end %>
        
    </div>
    

    
    <% if @link.errors.any? %> 

     <div class = "leftalign" id = "errors" align = "center">
      <div class = "animated flash"> 
    <%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved
    </div>
    </div>
    
    <div class = "leftalign" align = "center" >
   <% @link.errors.each do |error, msg| %> 
       
       <div class = "indent">
      <li> 
        <%= "#{error} #{msg}" %>
      </li>
      
        </div>
        
   <% end %>
   <% end %>
   


</body>
</html>

app/views/links/remove.js.erb
$("<%= "." + @link.name.gsub(" " , "") %><%= @link.upvotes %>").remove("");

app/views/links/report.html.erb
<!DOCTYPE html>
<html>
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
-->
 <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Roboto+Mono:400,700' rel='stylesheet' type='text/css'>

<head>
  <!--<link rel="stylesheet" href="animate.css">
  <link rel="stylesheet" href="bootstrap.css">-->
</head>
<body>
    <%= form_tag report_path, :method => :put do %>

   <!--<div class = "logo"> 
      <h1><b><center><font color="#99012">Patricelli Center for Social Entrepreneurship</font></center></b></h1>
   </div>-->
   <div class = "row"> 

  <h1><b><center> <br>
   <font face="Roboto Mono", color="#000000", size="70">PC<br>SE</font></center></b>
   </h1>
   </div>

  <h2><b><center> 
  <div class= "animated fadeIn">
   <font color="#99012">Report a Link</font></center></b>
   </h2></br>
   </div>
  <div class= "animated fadeIn">
   <p><i><center>An administrator will be notified of your link report for review.</center></i></p>
   </div>
   <div class="row">
            <div class="col-sm-12">
                <div class = "animated fadeIn">
                <center><p><b>What link would you like to report?</b></p></center>
                
                <%= text_field_tag :reportname, session[:reportname] %>
                <% session[:reportname] = nil %>
                
                </div>
            </div>
    </div>
<div class = "animated fadeIn"> 
        <!--<div class "row">-->
            <div class="col-xs-4 col-xs-offset-4">
                    <center><b>Why are you reporting this link?</b></center></br>
            </div>
            
            <div class="col-xs-5 col-xs-offset-4">
                    <label>
                        <%= radio_button_tag :reportreason, 'Broken Link', true %>
                        &nbsp;&nbsp;<span style="font-weight:normal;">Broken Link</span>
                    </label></br></br>
                    <label>
                        <%= radio_button_tag :reportreason, 'Miscategorized/mislabeled Link' %>
                        &nbsp;&nbsp;<span style="font-weight:normal;">Miscategorized/mislabeled Link</span>
                    </label></br></br>
                    <label>
                        <%= radio_button_tag :reportreason, 'Inappropriate Link' %>
                        &nbsp;&nbsp;<span style="font-weight:normal;">Inappropriate Link</span>
                    </label></br></br>
                    <label>
                        <%= radio_button_tag :reportreason, 'Other' %>
                        &nbsp;&nbsp;<span style="font-weight:normal;">Other:
                        <%= text_field_tag :otherreportreason, '', size: "45" %></span>
                    </label>
            </div>
        <!--</div>-->
        
        <div class = "row">
            <div class="col-xs-2 col-xs-offset-5">
                <div align="center">
                    <br>
                <%= button_tag(type: 'submit', class: "btn btn-large btn-search btn-danger") do %>
                     <i class="icon icon-search"></i> Report
                <% end %>
                <%= link_to "Back", links_path %>
                </div>
            </div>
            
        </div>
        
     
         <div class = "leftalign" id = "errors" align = "center">
      <div class = "animated flash"> 
          <%= session[:report_error] %>
          <% session[:report_error] = nil %>
    </div>
    </div>
    
        
        

    <% end %>
    </div>
</body>
</html>

app/views/links/show.html.erb
<!DOCTYPE html>
<html>
</html>